### ISSUE TITLE
Both domains fail to launch on kodi 19

### ISSUE THREAD

**Issue by pitsi** [bugatsinho/bugatsinho.github.io#85]
Now that cartoonsgr supports and starts on kodi 19, I decided to use it. And it fails to launch for both domains listed at its main screen. When pressing the festive entry, this comes up in the log

```
2021-11-02 13:27:00.957 T:3666    ERROR <general>: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                                    - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                                   Error Type: <class 'AttributeError'>
                                                   Error Contents: 'HTMLParser' object has no attribute 'unescape'
                                                   Traceback (most recent call last):
                                                     File "/home/user/.kodi/addons/plugin.video.cartoonsgr/default.py", line 1082, in <module>
                                                       teniesonline.metaglotismeno(url)
                                                     File "/home/user/.kodi/addons/plugin.video.cartoonsgr/resources/lib/indexers/teniesonline.py", line 49, in metaglotismeno
                                                       desc = client.replaceHTMLCodes(plot)
                                                     File "/home/user/.kodi/addons/plugin.video.cartoonsgr/resources/lib/modules/client.py", line 417, in replaceHTMLCodes
                                                       txt = HTMLParser.HTMLParser().unescape(txt)
                                                   AttributeError: 'HTMLParser' object has no attribute 'unescape'
                                                   -->End of Python script error report<--
                                                   
2021-11-02 13:27:01.018 T:3666     INFO <general>: Python interpreter stopped

```
and when pressing any of the three entries under the gamato movies one, whis comes up
```
2021-11-02 13:29:57.768 T:3715    ERROR <general>: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                                    - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                                   Error Type: <class 'AttributeError'>
                                                   Error Contents: 'HTMLParser' object has no attribute 'unescape'
                                                   Traceback (most recent call last):
                                                     File "/home/user/.kodi/addons/plugin.video.cartoonsgr/default.py", line 1049, in <module>
                                                       gamato_kids(url)
                                                     File "/home/user/.kodi/addons/plugin.video.cartoonsgr/default.py", line 611, in gamato_kids
                                                       desc = client.replaceHTMLCodes(plot)
                                                     File "/home/user/.kodi/addons/plugin.video.cartoonsgr/resources/lib/modules/client.py", line 417, in replaceHTMLCodes
                                                       txt = HTMLParser.HTMLParser().unescape(txt)
                                                   AttributeError: 'HTMLParser' object has no attribute 'unescape'
                                                   -->End of Python script error report<--
                                                   
2021-11-02 13:29:57.822 T:3715     INFO <general>: Python interpreter stopped
```
It is practically the same error though, but in different parts of the addon.

Kodi 19.3 on linux x64, cartoonsgr 1.0.25 and english locale for kodi and the system too.
Everything works fine on kodi 18.9 on libreelec 9.2.6 x64.

**Comment by kolekan** [comment]
https://github.com/bugatsinho/bugatsinho.github.io/pull/86/commits/381f9790dcd3f9fcbfe8ff98a87c9bd4030e544e

**Comment by kolekan** [comment]
Possibly a fix https://github.com/bugatsinho/bugatsinho.github.io/pull/87/commits/8a1e12d3e297da406b7e9618b907dafccc55cb6d

**Comment by pitsi** [comment]
It did not work. Log output for the festive one
```
2021-11-03 08:45:27.002 T:13528   ERROR <general>: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                                    - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                                   Error Type: <class 'AttributeError'>
                                                   Error Contents: 'HTMLParser' object has no attribute 'unescape'
                                                   Traceback (most recent call last):
                                                     File "/home/user/.kodi/addons/plugin.video.cartoonsgr/default.py", line 1082, in <module>
                                                       teniesonline.metaglotismeno(url)
                                                     File "/home/user/.kodi/addons/plugin.video.cartoonsgr/resources/lib/indexers/teniesonline.py", line 49, in metaglotismeno
                                                       desc = client.replaceHTMLCodes(plot)
                                                     File "/home/user/.kodi/addons/plugin.video.cartoonsgr/resources/lib/modules/client.py", line 422, in replaceHTMLCodes
                                                       txt = HTMLParser.HTMLParser().unescape(txt)
                                                   AttributeError: 'HTMLParser' object has no attribute 'unescape'
                                                   -->End of Python script error report<--
```
and for the ones under gamato movies
```
2021-11-03 08:45:46.930 T:13547   ERROR <general>: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                                    - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                                   Error Type: <class 'AttributeError'>
                                                   Error Contents: 'HTMLParser' object has no attribute 'unescape'
                                                   Traceback (most recent call last):
                                                     File "/home/jim/.kodi/addons/plugin.video.cartoonsgr/default.py", line 1049, in <module>
                                                       gamato_kids(url)
                                                     File "/home/jim/.kodi/addons/plugin.video.cartoonsgr/default.py", line 611, in gamato_kids
                                                       desc = client.replaceHTMLCodes(plot)
                                                     File "/home/jim/.kodi/addons/plugin.video.cartoonsgr/resources/lib/modules/client.py", line 422, in replaceHTMLCodes
                                                       txt = HTMLParser.HTMLParser().unescape(txt)
                                                   AttributeError: 'HTMLParser' object has no attribute 'unescape'
                                                   -->End of Python script error report<--
```
Proof that client.py is patched from line 417 to 421 as in your commit. I actually deleted the original file and downloaded yours. 
```
$ sed '417,421!d' .kodi/addons/plugin.video.cartoonsgr/resources/lib/modules/client.py 
    if six.PY3:
        import html
        txt = html.unescape(txt)
    else:
        txt = HTMLParser.HTMLParser().unescape(txt)
```

**Comment by kolekan** [comment]
Try this one
https://github.com/bugatsinho/bugatsinho.github.io/pull/87/commits/150e5d923b909f88a0d3c4685d01ea7bc2729d4e

**Comment by kolekan** [comment]
I correct it. Try this one
https://github.com/bugatsinho/bugatsinho.github.io/pull/88/commits/39d89b4cfda1ed5f1d2bce0309753f795e76e3f3

**Comment by pitsi** [comment]
Almost! Now the festive one does not launch only and pops this error
```
2021-11-03 14:06:22.775 T:5206    ERROR <general>: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                                    - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                                   Error Type: <class 'TypeError'>
                                                   Error Contents: cannot use a string pattern on a bytes-like object
                                                   Traceback (most recent call last):
                                                     File "/home/user/.kodi/addons/plugin.video.cartoonsgr/default.py", line 1082, in <module>
                                                       teniesonline.metaglotismeno(url)
                                                     File "/home/user/.kodi/addons/plugin.video.cartoonsgr/resources/lib/indexers/teniesonline.py", line 61, in metaglotismeno
                                                       title = clear_Title(title)
                                                     File "/home/user/.kodi/addons/plugin.video.cartoonsgr/resources/lib/indexers/teniesonline.py", line 178, in clear_Title
                                                       txt = re.sub('<.+?>', '', txt)
                                                     File "/usr/lib/python3.9/re.py", line 210, in sub
                                                       return _compile(pattern, flags).sub(repl, string, count)
                                                   TypeError: cannot use a string pattern on a bytes-like object
                                                   -->End of Python script error report<--

```
The other one does work though.

One more thing I noticed on kodi 19 is that there are no posters for the videos. Again, posters show up fine on kodi 18.

**Comment by host505** [comment]
Festive category comes from tenies-online, which hasn't been converted to be py3 compliant, there are many adjustments to be made for it.
I've got it working, but doesn't really worth it, most of their links are dead.

**Comment by pitsi** [comment]
Feel free to remove it then.

**Comment by host505** [comment]
There used to be a section for that site, with a couple of (kids related) categories in it.
I think @bugatsinho removed it because the site implemented some anti-bot measures we couldn't bypass. This is no longer the case, but maybe it's triggered over certain traffic.
Code's still there (commented out), I've made it py3 compliant, so if @bugatsinho wants it back in I can pr.

> Feel free to remove it then.

Thanks for the freedom, but what goes in/out of the add-on is subject to it's author.

**Comment by bugatsinho** [comment]
sorry guys but i was really busy lately. No much time for Kodi stuff. i've checked the PR @kolekan and merged it. Also feel free to share any other website with kids content.

**Comment by bugatsinho** [comment]
CartoonsGR updated to 1.0.26 
  - Kodi 19.x compatibility
  - fix gamato link regex
  - fix trailer link regex
[commit](https://github.com/bugatsinho/bugatsinho.github.io/commit/e08528224573f65d49547b8e21bbe69403de8970)

**Comment by bugatsinho** [comment]
> There used to be a section for that site, with a couple of (kids related) categories in it. I think @bugatsinho removed it because the site implemented some anti-bot measures we couldn't bypass. >

i still getting anti-bot protection but because of my location. if i use Greek IP with VPN then i can access directly the website. So if you want to make a PR you are more than welcome mate

**Comment by host505** [comment]
ok
https://github.com/bugatsinho/bugatsinho.github.io/pull/90

**Comment by pitsi** [comment]
Can I close this? I just realised there is an update.
The festive category still does not work though.

**Comment by kolekan** [comment]
@pitsi did you try this https://github.com/host505/random/blob/main/plugin.video.cartoonsgr-1.0.26a.zip ?

**Comment by pitsi** [comment]
No, because it not in the repo, so as to install fresh, and it obviously (an existing installation) did not upgrade to it but to 1.0.26.
Is it kodi 18 and 19 compatible?

**Comment by pitsi** [comment]
So I just installed it on kodi 18. There are 2 issues that are visible after a couple of seconds of usage and probably both are related to the new domain (tainies-online) itself.
ALL subcategories under there have the same content and there are almost no playable sources.
